# Import pandas to load our clean CSV data
import pandas as pd
# Import the Random Forest models for both Points (Regressor) and Win/Loss (Classifier)
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
# Import train_test_split to hide some games from the model to test its real accuracy
from sklearn.model_selection import train_test_split
# Import the math functions to grade the model's test
from sklearn.metrics import mean_absolute_error, accuracy_score
import os

# --- 1. LOAD THE ENGINEERED DATA ---
file_path = "assets/data/ml_features.csv"

# Check if the feature file exists
if not os.path.exists(file_path):
    print(f"Error: {file_path} not found. Run feature_engineering.py first!")
    exit()

# Load the CSV file into pandas
df = pd.read_csv(file_path)

# --- 2. PREPARE THE DATA FOR THE TEST ---
# Define our Inputs (X) - These are ONLY the pre-game rolling stats
X = df[['pregame_rolling_pts', 'pregame_rolling_reb', 'pregame_rolling_to', 
        'pregame_rolling_paint', 'pregame_win_streak']]

# Define our Targets (y)
y_pts = df['target_ncat_pts'] # The exact points the Aggies scored
y_win = df['target_win']      # Whether they won (1) or lost (0)

# The Magic Trick: Split the data! 
# test_size=0.2 means 20% of the games (about 5-6 games) are hidden for the final test.
# random_state=42 ensures the random split is exactly the same every time you run the script.
X_train, X_test, y_pts_train, y_pts_test, y_win_train, y_win_test = train_test_split(
    X, y_pts, y_win, test_size=0.2, random_state=42
)

print(f"Training on {len(X_train)} games. Testing predictions on {len(X_test)} hidden games...\n")

# --- 3. PREDICTING POINTS (Random Forest Regressor) ---
print("--- RANDOM FOREST: Predicting NC A&T Points ---")

# Initialize the model. n_estimators=100 means we are building 100 decision trees!
rf_regressor = RandomForestRegressor(n_estimators=100, random_state=42)

# Train the model using the 80% visible data
rf_regressor.fit(X_train, y_pts_train)

# Force the model to guess the points for the 20% hidden games
pts_predictions = rf_regressor.predict(X_test)

# Grade the test
pts_error = mean_absolute_error(y_pts_test, pts_predictions)
print(f"Real-World Accuracy: On unseen games, the model is off by an average of {round(pts_error, 1)} points.")

# Show exactly which pre-game stats the 100 trees cared about the most
print("\nFeature Importance (What drives the score?):")
# Zip matches the column names to the importance scores generated by the model
for feature, importance in zip(X.columns, rf_regressor.feature_importances_):
    print(f"  - {feature}: {round(importance * 100, 1)}%")


# --- 4. PREDICTING WINS (Random Forest Classifier) ---
print("\n--- RANDOM FOREST: Predicting Win/Loss ---")

# Initialize the Classifier model
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model using the 80% visible data
rf_classifier.fit(X_train, y_win_train)

# Force the model to guess who won the 20% hidden games
win_predictions = rf_classifier.predict(X_test)

# Grade the test
win_accuracy = accuracy_score(y_win_test, win_predictions)
print(f"Real-World Accuracy: Correctly predicted the Winner {round(win_accuracy * 100, 1)}% of the time on unseen games.")

# Show exactly which pre-game stats the 100 trees used to decide the winner
print("\nFeature Importance (What drives winning?):")
for feature, importance in zip(X.columns, rf_classifier.feature_importances_):
    print(f"  - {feature}: {round(importance * 100, 1)}%")